### ISSUE TITLE
What am I missing?

### ISSUE THREAD

**Issue by ghost** [thierrymichel/vue-svg-sprite#7]
Hey! I tried using it with the default configuration of the latest vue-cli (3.0.0-rc.3), but it didn't work.

## Filetree:
![image](https://user-images.githubusercontent.com/38450508/42122434-73682110-7c5f-11e8-874c-f94b9c6c0295.png)

### vue.config.js:
```
module.exports = {};
```

### main.js
```
...
import SvgSprite from "vue-svg-sprite";
Vue.use(SvgSprite);
...
```

### src\assets\svg\sprite.svg
```
...
<symbol id="icon-trash-o" viewBox="0 0 22 28">
<title>trash-o</title>
<path d="M8 11.5v9c0 0.281-0.219 0.5-0.5 0.5h-1c-0.281 0-0.5-0.219-0.5-0.5v-9c0-0.281 0.219-0.5 0.5-0.5h1c0.281 0 0.5 0.219 0.5
...
```

### TodoOptions.vue
```
...
<svg v-svg symbol="icon-trash" size="0 0 24 24" role="presentation" />
...
```

## The output I get:
![image](https://user-images.githubusercontent.com/38450508/42122346-f9ffbd7a-7c5d-11e8-9aa7-23f280e4fe02.png)

## DOM:
![image](https://user-images.githubusercontent.com/38450508/42122324-afcf068e-7c5d-11e8-9908-5835fb034012.png)

What am I missing?

**Comment by thierrymichel** [comment]
Hi @shravan-kaushik,

Thanks for using vue-svg-sprite.

The DOM output seems correct. 
Is your `/assets/svg/sprite.svg` available ? If you check the network tab in the devtools, do you have `200` or `404` ?

Regarding on how you build your project, the SVG file have to be in your "dist / public" folder.
I do not use `vue-cli` because I have my own files/folders architecture.
And I use webpack only for JS bundle, not for other files/dependencies.

You should find some help [here](https://cli.vuejs.org/guide/html-and-static-assets.html#static-assets-handling).

If you still have problem, do not hesitate to come back with some repo/pen/jsbin/…

Best regards,
Thierry

**Comment by ghost** [comment]
Thanks @thierrymichel! I'll take a look at the link and try what it says (as soon as I can) and close the issue if I find a robust solution.

**Comment by jwhitmarsh** [comment]
@shravan-kaushik Not sure if you resolved this, but in my case it's because projects setup with the Vue CLI use the file loader to load svgs and applies a hash (so `/assets/svg/sprite.svg` is turned into `/img/sprite.{hash}.svg`).

You can use `vue-svg-sprite` like:

```
Vue.use(SvgSprite, {
  url: require('./assets/svg/sprite.svg'),
});
```

`require('./assets/svg/sprite.svg')` will return the hashed path. 

FYI I spotted this by reviewing the default Webpack config that Vue CLI generates - you can do this by running `vue inspect > vue-webpack-config.js`

**Comment by ghost** [comment]
@jwhitmarsh Thank you, James! I almost forgot about this one as I've gotten used to importing SVGs individually. But I'll try this out the next time I need to use a sprite.
